name: Auto Building Runner
run-name: ${{ github.actor }} Auto Building Runner 🚀
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Building DEB
        run: |
          # 配置环境
          sudo apt update
          sudo apt install git dpkg-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qt5-qmake -y
          git clone https://github.com/gfdgd-xi/waydroid-runner
          cd waydroid-runner
          make build
          mv spark-waydroid-runner.deb ~
      - name: upload result
        uses: actions/upload-artifact@v1
        with:
          name: spark-waydroid-runner.deb
          path: /home/runner/spark-waydroid-runner.deb
      
      
    