name: Auto Get Waydroid
run-name: ${{ github.actor }} Auto Get Waydroid 🚀
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get
        run: |
          # 配置环境
          sudo apt update
          sudo apt install curl -y
          curl https://repo.waydro.id | sudo bash
          apt download waydroid python3-gbinder
          apt depends python3-gbinder


      
    