name: Auto Get Waydroid Image
run-name: ${{ github.actor }} Auto Get Waydroid Image 🚀
on:
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get
        run: |
          # 配置环境
          sudo apt update
          sudo apt install aria2 curl qemu-utils -y
          aria2c -x 16 -s 16 https://jihulab.com/gfdgd-xi/waydroid-image/-/raw/main/houdini-install.tar.gz -d /tmp
          cd /tmp
          tar -xvf houdini-install.tar.gz
          #curl https://repo.waydro.id | sudo bash
          #sudo apt install waydroid -y
          #sudo waydroid init -s GAPPS -f
          url=https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230422-GAPPS-waydroid_x86_64-system.zip/download
          aria2c -x 16 -s 16 $url
          unzip `basename $url`
          qemu-img resize system.img +1G
          sudo modprobe nbd max_ports=8
          qemn-nbd system.img --connect=/dev/nbd0
          resize2fs -p /dev/nbd0
          mkdir /tmp/mount
          cp /tmp/houdini-install/overlay/system/* /tmp/mount -rv
          umount /tmp/mount

          
      - name: upload result(system.img)
        uses: actions/upload-artifact@v1
        with:
          name: system.img
          path: /tmp/system.img
      #- name: upload result(vendor.img)
       # uses: actions/upload-artifact@v1
       # with:
        #  name: vendor.img
         # path: /usr/share/waydroid-extra/images/vendor.img
  

      
    